# Generated by Django 3.0.10 on 2021-01-22 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_mail', models.EmailField(max_length=254)),
                ('group_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_group', to='viewer.Group')),
                ('role', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_role', to='viewer.Role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
