# Generated by Django 3.0.10 on 2021-01-22 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_test', to='viewer.Course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField()),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.Attachment')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_test', to='testsheet.Test')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='question_type', to='testsheet.QuestionType')),
            ],
        ),
        migrations.CreateModel(
            name='TestTeacherAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=128)),
                ('correct', models.BooleanField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsheet.TestQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='TestStudentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='testsheet.TestQuestion')),
            ],
        ),
    ]
